repos:
  # core utility hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # latest stable
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace # ← correct id
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0  # use the actual tag name (no "prettier@" prefix)
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md|ya?ml)$

  # eslint 9 flat-config
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.29.0
    hooks:
      - id: eslint
        name: eslint-flat
        files: \.(js|jsx|ts|tsx|mjs|cjs)$
        args:
          - --config
          - eslint.config.cjs # see §2
          - --fix
        additional_dependencies:
          - eslint@9.29.0
          - "@eslint/js@9.29.0"
          - globals@^13
          - eslint-plugin-react-hooks@^4
          # add more plugins here as you need them

  # local TypeScript check
  - repo: local
    hooks:
      - id: tsc
        name: TypeScript type-check
        language: node
        entry: npx tsc -p tsconfig.json --noEmit
        pass_filenames: false
        additional_dependencies:
          - typescript@^5

  # commit-message lint
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint